### ISSUE TITLE
Mediainfo not working on 24.10.1

### ISSUE THREAD

**Issue by harshithmohan** [jlesage/docker-filebot#112]
### Current Behavior

Trying to rename a few series files using the following format:
`{jellyfin.tail} ({vf} {vc} {ac})`

Example file:
The Devil's Hour S02E01

But the output is coming as:
The Devil's Hour (2022) - S02E01 - DI Chambers ().mkv

It's missing the media info. It's working perfectly on 24.09.1

### Expected Behavior

Correct output filename:
The Devil's Hour (2022) - S02E01 - DI Chambers (1080p HEVC AAC).mkv

### Steps To Reproduce

Try to rename a file with the format containing any media info such as video resolution/codec or audio codec

### Environment

- OS: Unraid
- OS version: 6.1.106
- CPU: Intel  i7-12700
- Docker version: 24.0.9
- Device model: Custom server
- Browser/OS: Brave on macOS

### Container creation

```
networks:
  traefik:
    external: true

services:
  filebot:
    image: jlesage/filebot:latest
    container_name: filebot
    restart: always
    networks:
      - traefik
    environment:
      - USER_ID=99
      - GROUP_ID=100
      - UMASK=0000
      - TZ=Asia/Kolkata
      - AMC_INTERVAL=300
      - AMC_INPUT_STABLE_TIME=10
      - AMC_ACTION=move
      - AMC_CONFLICT=auto
      - AMC_MATCH_MODE=strict
      - AMC_ARTWORK=n
      - AMC_LANG=English
      - AMC_MOVIE_FORMAT=${MOVIE_FORMAT}
      - AMC_SERIES_FORMAT=${SERIES_FORMAT}
      - AMC_PROCESS_MUSIC=n
    volumes:
      - "/mnt/user/docker/filebot:/config"
      - "/mnt/user:/storage"
      - "/mnt/user/downloads/filebot:/watch"
      - "/mnt/user/media:/output"
```

### Container log

```text
[filebot-info] MediaInfo: java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
[filebot-info] Tools: fpcalc/1.5.1 7z/17.04 unrar/6.12
[filebot-info] Extended Attributes: OK
[filebot-info] Unicode Filesystem: OK
[filebot-info] Script Bundle: 2024-10-16 (r986)
[filebot-info] Groovy: 4.0.21
[filebot-info] JRE: OpenJDK Runtime Environment 17.0.10
[filebot-info] JVM: OpenJDK 64-Bit Server VM
[filebot-info] System Property: net.filebot.theme=System
[filebot-info] CPU/MEM: 20 Core / 16 GB Max Memory / 51 MB Used Memory
[filebot-info] OS: Linux (amd64)
[filebot-info] HW: Linux 086af359b163 6.1.106-Unraid #1 SMP PREEMPT_DYNAMIC Wed Aug 21 23:36:07 PDT 2024 x86_64 GNU/Linux
[filebot-info] CPU/MEM: : 12th Gen Intel(R) Core(TM) i7-12700 / MemTotal: 67 GB / MemFree: 5 GB / MemAvailable: 30 GB
[filebot-info] STORAGE: btrfs [/] @ 166 GB | fuse.shfs [/storage] @ 25 TB | fuse.shfs [/watch] @ 8 TB | fuse.shfs [/output] @ 25 TB | fuse.shfs [/config] @ 428 GB
[filebot-info] UID/GID: uid=99(app) gid=100(app) groups=100(app)
[filebot-info] DATA: /config
[filebot-info] Package: DOCKER
[filebot-info] License: FileBot License P55775581 (Valid-Until: 2024-12-10)
[filebot-info] Done ヾ(＠⌒ー⌒＠)ノ
[supervisor  ] service 'filebot-info' exited (with status 0).
[supervisor  ] starting service 'app'...
[supervisor  ] starting service 'amc'...
[amc         ] Changes detected in input folder.
[amc         ] Waiting 10 seconds before proceeding...
[supervisor  ] all services started.
[xvnc        ] Sat Oct 19 11:43:21 2024
[xvnc        ]  Connections: accepted: /tmp/vnc.sock
[xvnc        ]  SConnection: Client needs protocol version 3.8
[xvnc        ]  SConnection: Client requests security type None(1)
[xvnc        ]  VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
[xvnc        ]  VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian bgr888
[xvnc        ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
[xvnc        ]  ComparingUpdateTracker: (1:-nan ratio)
[app         ] Failed to retrieve parent window ID: java.lang.Error:
[app         ] There is an incompatible JNA native library installed on this system
[app         ] Expected: 7.0.0
[app         ] Found:    6.1.3
[app         ] (at /usr/lib/libjnidispatch.so).
[app         ] To resolve this issue you may do one of the following:
[app         ]  - remove or uninstall the offending library
[app         ]  - set the system property jna.nosys=true
[app         ]  - set jna.boot.library.path to include the path to the version of the
[app         ]    jnidispatch library included with the JNA jar file you are using
```

Was able to get only this much of the container logs as I had the text in the terminal. Can't get the logs again as they are lost. But I think the issue is pretty clear.

```
[filebot-info] MediaInfo: java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
...
[app         ] There is an incompatible JNA native library installed on this system
[app         ] Expected: 7.0.0
[app         ] Found:    6.1.3
[app         ] (at /usr/lib/libjnidispatch.so).
```

**Comment by jlesage** [comment]
Thanks for reporting. For now, I reverted to the previous version of FileBot, the time I investigate and fix this.

**Comment by harshithmohan** [comment]
Works fine in 24.11.1. Thanks @jlesage!
